/**
 * Standard Trade Types
 *
 * Predefined trade types with JobTypeIds that organizations can select from.
 * Each organization can customize the rates for these standard types.
 */

export interface StandardTradeType {
  jobTypeId: number
  name: string
  description: string
  // Client billing rates
  clientHourlyRate: number
  clientFirstHourRate: number | null
  clientCalloutFee: number
  clientAfterHoursCalloutFee: number
  clientAfterHoursExtraPercent: number
  // Employee/Contractor default costs
  defaultEmployeeHourlyRate: number
  defaultEmployeeDailyRate: number | null
}

export const STANDARD_TRADE_TYPES: StandardTradeType[] = [
  {
    jobTypeId: 12070,
    name: 'Air Conditioning',
    description: 'Air conditioning installation, repair, and maintenance',
    clientHourlyRate: 120,
    clientFirstHourRate: 150,
    clientCalloutFee: 80,
    clientAfterHoursCalloutFee: 150,
    clientAfterHoursExtraPercent: 50,
    defaultEmployeeHourlyRate: 45,
    defaultEmployeeDailyRate: 350,
  },
  {
    jobTypeId: 12022,
    name: 'Antennas',
    description: 'Antenna installation and repair services',
    clientHourlyRate: 110,
    clientFirstHourRate: 140,
    clientCalloutFee: 70,
    clientAfterHoursCalloutFee: 130,
    clientAfterHoursExtraPercent: 50,
    defaultEmployeeHourlyRate: 40,
    defaultEmployeeDailyRate: 320,
  },
  {
    jobTypeId: 3300,
    name: 'Appliance Repair',
    description: 'Household appliance repair and maintenance',
    clientHourlyRate: 120,
    clientFirstHourRate: 150,
    clientCalloutFee: 80,
    clientAfterHoursCalloutFee: 150,
    clientAfterHoursExtraPercent: 50,
    defaultEmployeeHourlyRate: 45,
    defaultEmployeeDailyRate: 350,
  },
  {
    jobTypeId: 3700,
    name: 'Bricklaying',
    description: 'Bricklaying and masonry services',
    clientHourlyRate: 95,
    clientFirstHourRate: 120,
    clientCalloutFee: 60,
    clientAfterHoursCalloutFee: 120,
    clientAfterHoursExtraPercent: 50,
    defaultEmployeeHourlyRate: 35,
    defaultEmployeeDailyRate: 280,
  },
  {
    jobTypeId: 12051,
    name: 'Cabinet Making',
    description: 'Custom cabinet design and installation',
    clientHourlyRate: 110,
    clientFirstHourRate: 140,
    clientCalloutFee: 70,
    clientAfterHoursCalloutFee: 140,
    clientAfterHoursExtraPercent: 50,
    defaultEmployeeHourlyRate: 40,
    defaultEmployeeDailyRate: 320,
  },
  {
    jobTypeId: 3900,
    name: 'Carpentry',
    description: 'General carpentry and woodworking services',
    clientHourlyRate: 110,
    clientFirstHourRate: 140,
    clientCalloutFee: 70,
    clientAfterHoursCalloutFee: 140,
    clientAfterHoursExtraPercent: 50,
    defaultEmployeeHourlyRate: 40,
    defaultEmployeeDailyRate: 320,
  },
  {
    jobTypeId: 12033,
    name: 'Carpet Cleaning',
    description: 'Professional carpet cleaning services',
    clientHourlyRate: 70,
    clientFirstHourRate: 90,
    clientCalloutFee: 50,
    clientAfterHoursCalloutFee: 100,
    clientAfterHoursExtraPercent: 50,
    defaultEmployeeHourlyRate: 25,
    defaultEmployeeDailyRate: 200,
  },
  {
    jobTypeId: 4000,
    name: 'Carpet Laying',
    description: 'Carpet installation and repair',
    clientHourlyRate: 95,
    clientFirstHourRate: 120,
    clientCalloutFee: 60,
    clientAfterHoursCalloutFee: 120,
    clientAfterHoursExtraPercent: 50,
    defaultEmployeeHourlyRate: 35,
    defaultEmployeeDailyRate: 280,
  },
  {
    jobTypeId: 4100,
    name: 'Cleaning',
    description: 'General cleaning services',
    clientHourlyRate: 65,
    clientFirstHourRate: 85,
    clientCalloutFee: 45,
    clientAfterHoursCalloutFee: 90,
    clientAfterHoursExtraPercent: 50,
    defaultEmployeeHourlyRate: 25,
    defaultEmployeeDailyRate: 200,
  },
  {
    jobTypeId: 4700,
    name: 'Electrical',
    description: 'Licensed electrical services',
    clientHourlyRate: 110,
    clientFirstHourRate: 140,
    clientCalloutFee: 70,
    clientAfterHoursCalloutFee: 140,
    clientAfterHoursExtraPercent: 50,
    defaultEmployeeHourlyRate: 40,
    defaultEmployeeDailyRate: 320,
  },
  {
    jobTypeId: 4800,
    name: 'Fencing',
    description: 'Fence installation and repair',
    clientHourlyRate: 90,
    clientFirstHourRate: 115,
    clientCalloutFee: 60,
    clientAfterHoursCalloutFee: 120,
    clientAfterHoursExtraPercent: 50,
    defaultEmployeeHourlyRate: 35,
    defaultEmployeeDailyRate: 280,
  },
  {
    jobTypeId: 12064,
    name: 'Glazing',
    description: 'Window and glass installation services',
    clientHourlyRate: 120,
    clientFirstHourRate: 150,
    clientCalloutFee: 80,
    clientAfterHoursCalloutFee: 150,
    clientAfterHoursExtraPercent: 50,
    defaultEmployeeHourlyRate: 45,
    defaultEmployeeDailyRate: 350,
  },
  {
    jobTypeId: 6500,
    name: 'Handyman',
    description: 'General handyman and maintenance services',
    clientHourlyRate: 85,
    clientFirstHourRate: 110,
    clientCalloutFee: 55,
    clientAfterHoursCalloutFee: 110,
    clientAfterHoursExtraPercent: 50,
    defaultEmployeeHourlyRate: 30,
    defaultEmployeeDailyRate: 240,
  },
  {
    jobTypeId: 6000,
    name: 'Landscaping',
    description: 'Landscape design and maintenance',
    clientHourlyRate: 75,
    clientFirstHourRate: 95,
    clientCalloutFee: 50,
    clientAfterHoursCalloutFee: 100,
    clientAfterHoursExtraPercent: 50,
    defaultEmployeeHourlyRate: 30,
    defaultEmployeeDailyRate: 240,
  },
  {
    jobTypeId: 6100,
    name: 'Lawn Mowing',
    description: 'Lawn mowing and garden maintenance',
    clientHourlyRate: 55,
    clientFirstHourRate: 70,
    clientCalloutFee: 40,
    clientAfterHoursCalloutFee: 80,
    clientAfterHoursExtraPercent: 50,
    defaultEmployeeHourlyRate: 22,
    defaultEmployeeDailyRate: 180,
  },
  {
    jobTypeId: 7200,
    name: 'Locksmithing',
    description: 'Lock installation and security services',
    clientHourlyRate: 120,
    clientFirstHourRate: 150,
    clientCalloutFee: 80,
    clientAfterHoursCalloutFee: 180,
    clientAfterHoursExtraPercent: 75,
    defaultEmployeeHourlyRate: 45,
    defaultEmployeeDailyRate: 350,
  },
  {
    jobTypeId: 7500,
    name: 'Painting',
    description: 'Interior and exterior painting services',
    clientHourlyRate: 70,
    clientFirstHourRate: 90,
    clientCalloutFee: 50,
    clientAfterHoursCalloutFee: 100,
    clientAfterHoursExtraPercent: 50,
    defaultEmployeeHourlyRate: 27,
    defaultEmployeeDailyRate: 220,
  },
  {
    jobTypeId: 10600,
    name: 'Pest Control',
    description: 'Pest inspection and treatment services',
    clientHourlyRate: 110,
    clientFirstHourRate: 140,
    clientCalloutFee: 70,
    clientAfterHoursCalloutFee: 140,
    clientAfterHoursExtraPercent: 50,
    defaultEmployeeHourlyRate: 40,
    defaultEmployeeDailyRate: 320,
  },
  {
    jobTypeId: 7900,
    name: 'Plastering',
    description: 'Plastering and rendering services',
    clientHourlyRate: 70,
    clientFirstHourRate: 90,
    clientCalloutFee: 50,
    clientAfterHoursCalloutFee: 100,
    clientAfterHoursExtraPercent: 50,
    defaultEmployeeHourlyRate: 27,
    defaultEmployeeDailyRate: 220,
  },
  {
    jobTypeId: 2600,
    name: 'Plumbing',
    description: 'Licensed plumbing services',
    clientHourlyRate: 110,
    clientFirstHourRate: 140,
    clientCalloutFee: 70,
    clientAfterHoursCalloutFee: 140,
    clientAfterHoursExtraPercent: 50,
    defaultEmployeeHourlyRate: 40,
    defaultEmployeeDailyRate: 320,
  },
  {
    jobTypeId: 8300,
    name: 'Roofing',
    description: 'Roof installation, repair, and maintenance',
    clientHourlyRate: 110,
    clientFirstHourRate: 140,
    clientCalloutFee: 70,
    clientAfterHoursCalloutFee: 140,
    clientAfterHoursExtraPercent: 50,
    defaultEmployeeHourlyRate: 40,
    defaultEmployeeDailyRate: 320,
  },
  {
    jobTypeId: 9400,
    name: 'Tiling',
    description: 'Floor and wall tiling services',
    clientHourlyRate: 85,
    clientFirstHourRate: 110,
    clientCalloutFee: 55,
    clientAfterHoursCalloutFee: 110,
    clientAfterHoursExtraPercent: 50,
    defaultEmployeeHourlyRate: 30,
    defaultEmployeeDailyRate: 240,
  },
]

// Helper function to get a trade type by JobTypeId
export function getStandardTradeType(jobTypeId: number): StandardTradeType | undefined {
  return STANDARD_TRADE_TYPES.find(t => t.jobTypeId === jobTypeId)
}

// Helper function to get trade type name by JobTypeId
export function getTradeTypeName(jobTypeId: number): string {
  return STANDARD_TRADE_TYPES.find(t => t.jobTypeId === jobTypeId)?.name || 'Unknown Trade'
}
